language: node_js

node_js:
  - "4"

before_install:
  - npm install -g npm

before_script:
  - npm install karma-cli -g

script: karma start --single-run --browsers PhantomJS --reporters progress,coverage,coveralls

notifications:
  email: false
